package seng302.util.map;

import seng302.util.object.XinityNote;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The song map class.
 */
public class SongMap {

    private static List<List<Integer>> beethoven = new ArrayList<>();
    private static List<List<Integer>> johnCena = new ArrayList<>();
    private static List<List<Integer>> gameOfThrones = new ArrayList<>();

    /**
     * Gets a map of not mapped to duration.
     *
     * @return The map.
     */
    public static List<List<Integer>> getBeethoven() {
        if (beethoven.size() < 1) {
            try {
                initializeBeethoven();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return beethoven;
    }

    /**
     * Gets a map of not mapped to duration.
     *
     * @return The map.
     */
    public static List<List<Integer>> getJohnCena() {
        if (johnCena.size() < 1) {
            try {
                initializeJohnCena();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return johnCena;
    }

    /**
     * Gets a map of not mapped to duration.
     *
     * @return The map.
     */
    public static List<List<Integer>> getGameOfThrones() {
        if (gameOfThrones.size() < 1) {
            try {
                initializeGameOfThrones();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return gameOfThrones;
    }

    /**
     * Sets up the beethoven list.
     *
     * @throws Exception Invalid note.
     */
    private static void initializeBeethoven() throws Exception {
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("e2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g#3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g#4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 1));  //
        beethoven.add(Arrays.asList(new XinityNote("e2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g#3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        /*beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("c3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("f5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d5").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("g2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("f4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("e2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e6").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("e2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g#3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g#4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d#5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("d5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("e2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("g#3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("c5").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("b4").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        beethoven.add(Arrays.asList(new XinityNote("a2").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("e3").getMidi(), 250));
        beethoven.add(Arrays.asList(new XinityNote("a3").getMidi(), 250));*/
    }

    /**
     * Sets up the john cena list.
     *
     * @throws Exception Invalid note.
     */
    private static void initializeJohnCena() throws Exception {
        /*johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1280));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1280));
        johnCena.add(Arrays.asList(new XinityNote("eb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("eb3").getMidi(), 1280));
        johnCena.add(Arrays.asList(new XinityNote("d2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1280));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 1280));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a5").getMidi(), 1280));
        johnCena.add(Arrays.asList(new XinityNote("eb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("eb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 1280));
        johnCena.add(Arrays.asList(new XinityNote("d2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 80));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 400));*/
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("c4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("a2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("c4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("c4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("a2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("c4").getMidi(), 320));
        /*johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a5").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("eb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("eb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("d2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("gb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("gb5").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("d2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("d2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("c4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("a2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("c4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("c4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("a2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("a5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("d4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("c4").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 480));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("bb5").getMidi(), 160));
        johnCena.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("f5").getMidi(), 320));
        johnCena.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g4").getMidi(), 1));
        johnCena.add(Arrays.asList(new XinityNote("g5").getMidi(), 160));*/
    }

    /**
     * Sets up the game of thrones list.
     *
     * @throws Exception Invalid note.
     */
    private static void initializeGameOfThrones() throws Exception {
        /*gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("e4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("e4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("e4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("e4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("e4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));*/
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb1").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("f3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("ab3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("ab3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("ab3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("ab3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        /*gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("c3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("eb4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("f4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d4").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("g3").getMidi(), 360));
        gameOfThrones.add(Arrays.asList(new XinityNote("g2").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("d3").getMidi(), 1));
        gameOfThrones.add(Arrays.asList(new XinityNote("bb3").getMidi(), 180));
        gameOfThrones.add(Arrays.asList(new XinityNote("c4").getMidi(), 180));*/
    }
}
